import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import 'primeflex/primeflex.scss';
import Navbar from "./Components/Layout/Navbar";
import ClientNavbarWrapper from "./Components/Layout/ClientNavbarWrapper";
 
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ClientNavbarWrapper/>
        {children}
      </body>
    </html>
  );
}
